#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          nlan
# Required-Start:    $network openvswitch-switch
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NLAN Agent
# Description:       NLAN Agent is an DevOps agent program
### END INIT INFO

[ -x /opt/nlan/nlan_agent.py ] || exit 0

start () {
    python /opt/nlan/nlan_agent.py --init start --debug > /tmp/nlan.log
}



case $1 in
    start)
        start
        ;;
    stop | force-stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0

